export const RECEIVE_USER_BALANCE = 'RECEIVE_USER_BALANCE';
export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
export const ADD_DATA_SOURCE = 'ADD_DATA_SOURCE';
export const VIP_LEVEL_UP = 'VIP_LEVEL_UP';
export const CHANGE_BALANCE = 'CHANGE_BALANCE';
