export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_USER_BALANCE = 'RECEIVE_USER_BALANCE';
export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
export const ADD_DATA_SOURCE = 'ADD_DATA_SOURCE';
